### ISSUE TITLE
module 'proximal' has no attribute 'patch_BM3D'

### ISSUE THREAD

**Issue by Benlawei** [tum-vision/learn_prox_ops#1]
Hello,I meet some issues,I use Ubuntu16.04 LTS and my gpu is GeForce GTX 1060 
when I use the command "python3 src/experiment_demosaicking.py grid_search_all_images with elemental.denoising_prior=BM3D",I got a Traceback "AttributeError: module 'proximal' has no attribute 'patch_BM3D'",but I can find "patch_NLM" in the path "proximal/prox_fns/patch_NLM.py",Is it missing a "patch_BM3D.py" there?

**Comment by timmeinhardt** [comment]
Hello and thank you for your interest in our research. 
In order to use our code you should follow the installation steps in our `README.rst`. Your error comes from using the official `ProxImaL` package instead of our own modified version. Please install our version with `pip3 install git+https://github.com/timmeinhardt/ProxImaL@learn_prox_ops`. This includes the BM3D denoising proximal function.

If this resolves your issue please close it and do not hesitate to ask if you encounter further problems!

**Comment by Benlawei** [comment]
Thank u,I have followed the installation steps and solved above problem.
But when I use `python3 src/experiment_deblurring.py with experiment_name=experiment_a image_name=barbara elemental.optimal_DNCNN_experiment_a`,I got a lot of Traceback,such as:
INFO:tensorflow:Restoring parameters from models/DNCNN__gaussian_0.02__40-40-1__128/model.ckpt
INFO - tensorflow - Restoring parameters from models/DNCNN__gaussian_0.02__40-40-1__128/model.ckpt
2018-04-06 20:21:00.430443: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: not an sstable (bad magic number)
...
DataLossError (see above for traceback): not an sstable (bad magic number)
	 [[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_5/tensor_names, save/RestoreV2_5/shape_and_slices)]]
	 [[Node: save/RestoreV2_14/_5 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_76_save/RestoreV2_14", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
I think there may be some problems when restoring parameters from checkpoint.

**Comment by timmeinhardt** [comment]
Could you please check if  your TensorFlow version is indeed `1.3.0`.

**Comment by Benlawei** [comment]
I used the command `pip3 install tensorflow-gpu==1.3.0`,and my TensorFlow version is tensorflow-gpu (1.3.0). In fact, I have used other  versions of the TensorFlow as an attempt，but I still got the same TraceBack .

**Comment by timmeinhardt** [comment]
And you also installed Git LSF and downloaded all the necessary model files? There must be three files in the corresponding subdirectory.

Edit.: I just reproduced the error when I clone the repository without Git LSF. Eventhough there are files in the model directories these are just 4kB placeholders.

**Comment by timmeinhardt** [comment]
@Benlawei Can we close this issue or did you encounter any other troubles?
