### ISSUE TITLE
No data/deblurring_grey file

### ISSUE THREAD

**Issue by ysnan** [tum-vision/learn_prox_ops#4]
I try to reproduce the experiments in Table 3 of your paper. When I run `python src/experiment_deblurring.py with experiment_name=experiment_a image_name=barbara elemental.optimal_DNCNN_experiment_a`, it fails with error 

```
File "/LearnProxOpt/src/data.py", line 75, in load_deblurring_grey_data
    experiment_data = experiments_data[experiment_name]
KeyError: 'experiment_a'
```
I found the reason coming from no file for 'data/deblurring_grey'. (See line 60 of ./src/data.py for more information)

Thank you!

**Comment by timmeinhardt** [comment]
Did you execute the `data/download_datasets.sh` script which downloads the data?

**Comment by ysnan** [comment]
Oh, no, I forget doing that! That is my fault! I will try this and thank you!

**Comment by timmeinhardt** [comment]
I hope you were able to resolve the issue. Is yes, can we close this issue?

**Comment by ysnan** [comment]
Yes, it has been resolved! It can be closed and thank you!
